prima: Fix definition of vos_process_bt_profile in vos_api
* Fixes build error since tag 'LA.UM.9.6.2.r1-03800-89xx.0'

Introduced in commit: 1982ed4d9cc3f6b3e026806d20fa419440339835

"wlan: Add support to send BT advertisement via bt_profile"

drivers/staging/prima/CORE/VOSS/inc/vos_api.h:627:1: error: expected identifier or '('
{
^